### ISSUE TITLE
Federated account sign in pop ups are blocked.

### ISSUE THREAD

**Issue by sach2211** [GoogleChrome/credential-management-sample#11] opened 2017-11-19 13:31 UTC
Scenario: 

- Users signs in with a federated account and chooses to save it.

- Now, after few days, lets assume the user is logged out from the federated account.

- Now, when user visits in our app again, the federated account authentication will kick in. This will involve a pop up (as user is signed out of federated account). But, the pop up will be blocked - As its a result of resolution of promise - `navigator.credentials.get`, not direct user action.

Any work around for this ?

**Comment by agektmr** [comment] 2017-11-27 08:11
Hi @sach2211 , this is a known issue mainly caused by Chrome:
https://crbug.com/404161

Please star it or comment it to encourage Chromium engineers to prioritize on it.

**Comment by agektmr** [comment] 2017-11-27 08:13
This is a duplicate of #5

**Closed by agektmr** 2017-11-27 08:13 UTC
